name: Daily ETL

on:
  schedule:
    - cron: "0 2 * * *"
    - cron: "0 16 * * *"

  workflow_dispatch:

jobs:

  etl:

    runs-on: ubuntu-latest
    environment: electricityenv

    steps:

      - uses: actions/checkout@v4
      - name: Run ETL
        env:
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
          ORACLE_DSN: ${{ secrets.ORACLE_DSN }}
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
          WALLET_ENCRIPTING_PASSWORD: ${{ secrets.WALLET_ENCRIPTING_PASSWORD }}
          ORACLE_WALLET_PASSWORD: ${{ secrets.ORACLE_WALLET_PASSWORD }}
          COUNTRY_CODE: "ES"
        run: |
          START_DATE=$(date -d "3 days ago" '+%Y-%m-%d') \
          END_DATE=$(date -d "yesterday" '+%Y-%m-%d') \
          docker compose up --abort-on-container-exit --exit-code-from uploader uploader