name: Daily ETL

on:
  schedule:
    - cron: "0 20 * * *"

  workflow_dispatch:

jobs:

  etl:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install .

      - name: Recreate Oracle wallet
        run: |
          mkdir wallet
          echo "${{ secrets.ORACLE_WALLET }}" | base64 --decode > wallet.zip
          unzip wallet.zip -d wallet

      - name: Run ETL
        env:
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
          ORACLE_DSN: ${{ secrets.ORACLE_DSN }}
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
          WALLET_LOCATION: wallet
          WALLET_PASSWORD: ${{ secrets.ORACLE_WALLET_PASSWORD }}
        run: |
          python upload_daily_data.py